name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change owner user
      run: make change-owner

    - name: Configure application
      run: make configure
      
    - name: Deploy application
      run: make up
      
    - name: Run tests
      run: make test
